[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase timeout for AI API functions
  timeout = 15
  # Set memory limit
  memory = 1024

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  # Optimize for faster builds
  NODE_OPTIONS = "--max-old-space-size=4096"